
name: Run Notebook

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install PyTorch and Torchvision with CUDA
      run: pip install torch==2.3.0+cu118 torchvision==0.18.0+cu118 -f https://download.pytorch.org/whl/torch_stable.html

    - name: Install the rest of the dependencies
      run: |
        pip install -r requirements.txt
    - name: Execute Jupyter Notebook
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        jupyter nbconvert --to notebook --execute Adamata_Technical_Test_Answer.ipynb --output executed_notebook.ipynb
